/**
 * src/services/daily-planner.ts
 * Generates a daily publishing plan.
 *
 * Every day, generates a new random schedule respecting:
 *   - posts/day (from config)
 *   - category distribution (A:2, B:1, C:1 by default)
 *   - enabled plugins
 *   - language
 *   - posting windows
 *   - minimum gap between posts
 *
 * See Prompt 9 spec.
 */

import { slotsKey } from "../core/storage/keys";
import { DailyPlanError } from "../core/scheduler/errors";
import type { DailyPlan, SlotTime } from "../types/scheduler";
import type { Category } from "../types/category";
import type { FredySettings } from "../types/config";
import type { TimeGenerator } from "./time-generator";
import type { KVStore } from "./kv-store";
import type { Logger } from "./logger";
import { formatDateInZone } from "../primitives/time";

export interface DailyPlannerDeps {
  readonly kv: KVStore;
  readonly logger: Logger;
  readonly timeGenerator: TimeGenerator;
  readonly settings: () => Promise<FredySettings>;
}

const PLAN_TTL_SECONDS = 48 * 3600; // 48 hours

export class DailyPlanner {
  constructor(private readonly deps: DailyPlannerDeps) {}

  /** Generate a new daily plan for today (or a specific date). */
  async generate(date?: string): Promise<DailyPlan> {
    const settings = await this.deps.settings();
    const scheduler = settings.scheduler;

    if (!scheduler.enabled) {
      throw new DailyPlanError("Scheduler is disabled");
    }

    // Determine the date.
    const targetDate = date ?? formatDateInZone(Date.now(), scheduler.timezone);

    // Build the category distribution from config.
    const distribution = this.buildDistribution(settings);

    // Validate that total matches postsPerDay.
    const total = Object.values(distribution).reduce((sum, n) => sum + n, 0);
    if (total !== settings.content.postsPerDay) {
      this.deps.logger.warn("scheduler.skip", {
        message: `Category distribution total (${total}) != postsPerDay (${settings.content.postsPerDay})`,
      });
    }

    // Generate random slot times.
    const slots: readonly SlotTime[] = this.deps.timeGenerator.generate(
      targetDate,
      scheduler,
      distribution,
    );

    if (slots.length === 0) {
      throw new DailyPlanError("No slots generated — check config");
    }

    const plan: DailyPlan = {
      date: targetDate,
      slots,
      generatedAt: Date.now(),
      timezone: scheduler.timezone,
      postsPerDay: settings.content.postsPerDay,
      categoryDistribution: distribution,
    };

    // Persist to KV.
    await this.deps.kv.setJson(slotsKey(targetDate), plan, PLAN_TTL_SECONDS);

    this.deps.logger.info("scheduler.slot_fired", {
      date: targetDate,
      slotCount: slots.length,
      timezone: scheduler.timezone,
      message: "Daily plan generated",
    });

    return plan;
  }

  /** Load today's plan from KV (or generate if missing).
   *  v7.4.3: Auto-detects stale plans generated by the buggy v7.4.1 code
   *  (which used Date.UTC instead of timezone-aware epochMs). If the first
   *  slot's epochMs doesn't match what we'd compute now, we regenerate the
   *  plan from scratch. This ensures the fix takes effect immediately
   *  without requiring the admin to manually call "Regenerate Plan". */
  async getOrGenerate(date?: string): Promise<DailyPlan> {
    const settings = await this.deps.settings();
    const targetDate = date ?? formatDateInZone(Date.now(), settings.scheduler.timezone);

    const existing = await this.deps.kv.getJson<DailyPlan>(slotsKey(targetDate));
    if (existing && existing.slots.length > 0) {
      // ── Stale plan detection ──
      // Recompute the first slot's epochMs with the FIXED timezone math.
      // If it doesn't match the stored value, the plan was generated by
      // the old buggy code → regenerate.
      const firstSlot = existing.slots[0]!;
      const [hh, mm] = firstSlot.time.split(":").map(Number);
      const expectedMinutes = (hh ?? 0) * 60 + (mm ?? 0);
      // Use the same TimeGenerator that generate() uses.
      const expectedEpochMs = this.computeExpectedEpochMs(targetDate, expectedMinutes, settings.scheduler.timezone);
      if (expectedEpochMs !== null && Math.abs(expectedEpochMs - firstSlot.epochMs) > 60_000) {
        // More than 1 minute difference → stale plan. Regenerate.
        this.deps.logger.warn("scheduler.stale_plan", {
          date: targetDate,
          storedEpochMs: firstSlot.epochMs,
          expectedEpochMs,
          diffMinutes: Math.round((firstSlot.epochMs - expectedEpochMs) / 60_000),
          message: "Stale plan detected (timezone bug) — regenerating",
        });
        // Also clear fired markers for this date so slots can re-fire.
        const firedKeys = await this.deps.kv.list(`fredy:sched:sent:${targetDate}:`);
        for (const k of firedKeys) {
          await this.deps.kv.delete(k).catch(() => {});
        }
        return this.generate(targetDate);
      }
      return existing;
    }

    return this.generate(targetDate);
  }

  /** Compute expected epochMs for a slot using the fixed timezone math.
   *  Returns null if the computation fails (shouldn't happen). */
  private computeExpectedEpochMs(date: string, minutes: number, timezone: string): number | null {
    try {
      const [year, month, day] = date.split("-").map(Number);
      const utcMidnight = Date.UTC(year!, month! - 1, day!, 0, 0, 0);
      const offsetMin = this.getTzOffsetMinutes(utcMidnight, timezone);
      return utcMidnight + (minutes - offsetMin) * 60_000;
    } catch {
      return null;
    }
  }

  /** Get timezone offset in minutes (positive = ahead of UTC). */
  private getTzOffsetMinutes(utcMs: number, timezone: string): number {
    try {
      const dtf = new Intl.DateTimeFormat("en-US", {
        timeZone: timezone,
        year: "numeric", month: "2-digit", day: "2-digit",
        hour: "2-digit", minute: "2-digit", second: "2-digit",
        hour12: false,
      });
      const parts = dtf.formatToParts(new Date(utcMs));
      const get = (type: string) => parts.find(p => p.type === type)?.value ?? "0";
      const y = Number(get("year"));
      const m = Number(get("month"));
      const d = Number(get("day"));
      const h = Number(get("hour")) === 24 ? 0 : Number(get("hour"));
      const mi = Number(get("minute"));
      const s = Number(get("second"));
      const asIfUtc = Date.UTC(y, m - 1, d, h, mi, s);
      return Math.round((asIfUtc - utcMs) / 60_000);
    } catch {
      return 0;
    }
  }

  /** Get the next unfired slot from today's plan. */
  async getNextSlot(now = Date.now()): Promise<{ slot: SlotTime; plan: DailyPlan } | null> {
    const plan = await this.getOrGenerate();
    for (const s of plan.slots) {
      if (s.epochMs <= now) continue;
      const fired = await this.isSlotFired(s);
      if (!fired) {
        return { slot: s, plan };
      }
    }
    return null;
  }

  /** Check if a slot has been fired. */
  async isSlotFired(slot: SlotTime): Promise<boolean> {
    const key = `fredy:sched:sent:${slot.date}:${slot.index}`;
    const value = await this.deps.kv.get(key);
    return value !== null;
  }

  /** Mark a slot as fired. */
  async markSlotFired(slot: SlotTime, contentId: string): Promise<void> {
    const key = `fredy:sched:sent:${slot.date}:${slot.index}`;
    await this.deps.kv.setJson(key, { contentId, firedAt: Date.now() }, PLAN_TTL_SECONDS);
  }

  /** Build category distribution from settings. */
  private buildDistribution(settings: FredySettings): Readonly<Record<Category, number>> {
    const cats = settings.categories;
    return {
      A: cats.A.enabled ? cats.A.dailyLimit : 0,
      B: cats.B.enabled ? cats.B.dailyLimit : 0,
      C: cats.C.enabled ? cats.C.dailyLimit : 0,
    };
  }

  /** Clear the plan for a date (for testing). */
  async clear(date: string): Promise<void> {
    await this.deps.kv.delete(slotsKey(date));
  }
}
