/**
 * src/types/strategy.ts
 * Strategy Engine types — defines the data shapes for the content
 * planning system (Phase 2).
 *
 * The Strategy Engine produces a DailyPublishPlan which the Scheduler
 * consumes. The engine never publishes — it only plans.
 */

import type { Category } from "./category";

// ────────────────────────────────────────────────────────────
// Strategy Modes
// ────────────────────────────────────────────────────────────

/** Built-in publishing strategies. */
export type StrategyMode =
  | "minimal"
  | "balanced"
  | "active"
  | "ai_priority"
  | "news_priority"
  | "custom";

/** Category distribution for a strategy. */
export interface StrategyDistribution {
  readonly A: number;
  readonly B: number;
  readonly C: number;
  readonly total: number;
}

/** Quality threshold override (for ai_priority strategy). */
export interface StrategyQualityOverride {
  readonly qualityThreshold?: number;
}

/** Complete strategy definition. */
export interface StrategyDefinition {
  readonly mode: StrategyMode;
  readonly name: string;
  readonly description: string;
  readonly distribution: StrategyDistribution;
  readonly qualityOverride?: StrategyQualityOverride;
}

// ────────────────────────────────────────────────────────────
// Weekly Themes
// ────────────────────────────────────────────────────────────

/** A daily theme with topics that influence provider selection. */
export interface DailyTheme {
  readonly day: number; // 0=Sunday, 1=Monday, ..., 6=Saturday
  readonly dayName: string;
  readonly topics: readonly string[];
}

/** Weekly theme configuration (7 days). */
export type WeeklyThemes = readonly DailyTheme[];

// ────────────────────────────────────────────────────────────
// Priority
// ────────────────────────────────────────────────────────────

/** Priority level for a planned post. */
export type PostPriority = "high" | "normal" | "low";

// ────────────────────────────────────────────────────────────
// Planned Post
// ────────────────────────────────────────────────────────────

/** A single planned post in a DailyPublishPlan. */
export interface PlannedPost {
  /** Unique ID for this planned post (e.g., "plan-2026-07-16-0"). */
  readonly id: string;
  /** Slot index (0-based, ordered by time). */
  readonly index: number;
  /** Date in YYYY-MM-DD format. */
  readonly date: string;
  /** Time in HH:MM format (random within posting window). */
  readonly time: string;
  /** Epoch milliseconds for the publish time. */
  readonly epochMs: number;
  /** Category for this post. */
  readonly category: Category;
  /** Preferred provider ID (influenced by weekly theme). */
  readonly provider: string | null;
  /** Strategy that generated this plan. */
  readonly strategy: StrategyMode;
  /** Language for this post. */
  readonly language: string;
  /** Priority level. */
  readonly priority: PostPriority;
  /** Queue target depth for this category. */
  readonly queueTarget: number;
  /** Current status. */
  readonly status: PlannedPostStatus;
  /** Posting window this post was assigned to. */
  readonly windowIndex: number;
  /** v9.2.3: Failure reason — populated when status is "failed" or "backup".
   *  Contains the actual error message (e.g., "AI generation failed: timeout"
   *  or "Telegram sendMessage failed: 400 Bad Request: message text is empty").
   *  Surfaced by the Manager UI when the admin clicks the ❌ Failed badge. */
  readonly error?: string | null;
  /** v9.2.3: Pipeline stage that failed (normalize/validate/dedup/ai_generate/
   *  quality_score/format/publish/queue/grace/pipeline). Useful for triaging
   *  recurring failures. */
  readonly failedStage?: string | null;
  /** v9.2.3: Epoch ms when the failure was recorded. */
  readonly failedAt?: number | null;
  /** v9.2.3: Plugin that was attempted when the failure occurred (may differ
   *  from `provider` if a fallback plugin was being tried). */
  readonly failedPlugin?: string | null;
}

/** Status of a planned post. */
export type PlannedPostStatus =
  | "pending"    // not yet due
  | "due"        // time has arrived, waiting for publish
  | "published"  // successfully published
  | "failed"     // publish failed, no backup succeeded
  | "backup"     // original failed but a backup plugin succeeded
  | "skipped";   // skipped (quiet hours, no content, etc.)

// ────────────────────────────────────────────────────────────
// Daily Publish Plan
// ────────────────────────────────────────────────────────────

/** Complete daily publishing plan generated by the Strategy Engine. */
export interface DailyPublishPlan {
  /** Date in YYYY-MM-DD format. */
  readonly date: string;
  /** Strategy that generated this plan. */
  readonly strategy: StrategyMode;
  /** Weekly theme for this day. */
  readonly theme: DailyTheme | null;
  /** All planned posts for the day, sorted by time. */
  readonly posts: readonly PlannedPost[];
  /** When this plan was generated. */
  readonly generatedAt: number;
  /** Timezone used for generation. */
  readonly timezone: string;
  /** Language for all posts in this plan. */
  readonly language: string;
  /** Category distribution used. */
  readonly distribution: StrategyDistribution;
  /** Validation result. */
  readonly validation: PlanValidationResult;
}

// ────────────────────────────────────────────────────────────
// Validation
// ────────────────────────────────────────────────────────────

/** Result of validating a daily plan. */
export interface PlanValidationResult {
  readonly valid: boolean;
  readonly errors: string[];
  readonly warnings: string[];
}
