/**
 * src/plugins/sources/night-music/hall-of-fame.ts
 * v13.2.0: Curated list of ~300 legendary songs for the Night Music quality gate.
 *
 * Sources: Rolling Stone Top 500, Billboard Greatest, Grammy winners,
 * Classic Rock Hall of Fame, Apple Music Essentials, Spotify Editorial.
 *
 * Format: "Song|Artist" — normalized to lowercase for matching.
 * The match is case-insensitive and ignores "feat." / "ft." suffixes.
 */

export interface HallOfFameEntry {
  readonly song: string;
  readonly artist: string;
  readonly era: "60s" | "70s" | "80s" | "90s" | "00s" | "10s" | "20s";
  readonly genre: "rock" | "pop" | "electronic" | "hiphop" | "classic" | "r&b" | "metal" | "indie";
}

/**
 * 300+ legendary songs. Each entry is a canonical "great song" that
 * is widely recognized and safe to publish.
 */
export const HALL_OF_FAME: readonly HallOfFameEntry[] = [
  // ─── 60s ───
  { song: "Hey Jude", artist: "The Beatles", era: "60s", genre: "rock" },
  { song: "Imagine", artist: "John Lennon", era: "70s", genre: "classic" },
  { song: "Yesterday", artist: "The Beatles", era: "60s", genre: "classic" },
  { song: "Let It Be", artist: "The Beatles", era: "70s", genre: "rock" },
  { song: "Come Together", artist: "The Beatles", era: "60s", genre: "rock" },
  { song: "Hotel California", artist: "Eagles", era: "70s", genre: "rock" },
  { song: "Bohemian Rhapsody", artist: "Queen", era: "70s", genre: "rock" },
  { song: "Stairway to Heaven", artist: "Led Zeppelin", era: "70s", genre: "rock" },
  { song: "Sweet Child O Mine", artist: "Guns N Roses", era: "80s", genre: "rock" },
  { song: "Smells Like Teen Spirit", artist: "Nirvana", era: "90s", genre: "rock" },
  { song: "Like a Rolling Stone", artist: "Bob Dylan", era: "60s", genre: "rock" },
  { song: "Paint It Black", artist: "The Rolling Stones", era: "60s", genre: "rock" },
  { song: "Gimme Shelter", artist: "The Rolling Stones", era: "60s", genre: "rock" },
  { song: "Satisfaction", artist: "The Rolling Stones", era: "60s", genre: "rock" },
  { song: "Respect", artist: "Aretha Franklin", era: "60s", genre: "r&b" },
  { song: "What a Wonderful World", artist: "Louis Armstrong", era: "60s", genre: "classic" },
  { song: "Blowin in the Wind", artist: "Bob Dylan", era: "60s", genre: "classic" },
  { song: "All Along the Watchtower", artist: "Jimi Hendrix", era: "60s", genre: "rock" },
  { song: "Purple Haze", artist: "Jimi Hendrix", era: "60s", genre: "rock" },
  { song: "A Day in the Life", artist: "The Beatles", era: "60s", genre: "rock" },
  { song: "Bridge Over Troubled Water", artist: "Simon Garfunkel", era: "70s", genre: "classic" },
  { song: "The Sound of Silence", artist: "Simon Garfunkel", era: "60s", genre: "classic" },
  { song: "Mrs Robinson", artist: "Simon Garfunkel", era: "60s", genre: "classic" },
  { song: "California Dreamin", artist: "The Mamas the Papas", era: "60s", genre: "classic" },
  { song: "Unchained Melody", artist: "Righteous Brothers", era: "60s", genre: "classic" },
  { song: "Stand By Me", artist: "Ben E King", era: "60s", genre: "classic" },
  { song: "I Heard It Through the Grapevine", artist: "Marvin Gaye", era: "60s", genre: "r&b" },
  { song: "My Girl", artist: "The Temptations", era: "60s", genre: "r&b" },
  { song: "Dancing in the Street", artist: "Martha Reeves Vandellas", era: "60s", genre: "r&b" },

  // ─── 70s ───
  { song: "Dream On", artist: "Aerosmith", era: "70s", genre: "rock" },
  { song: "Free Bird", artist: "Lynyrd Skynyrd", era: "70s", genre: "rock" },
  { song: "More Than a Feeling", artist: "Boston", era: "70s", genre: "rock" },
  { song: "Carry On Wayward Son", artist: "Kansas", era: "70s", genre: "rock" },
  { song: "Dust in the Wind", artist: "Kansas", era: "70s", genre: "rock" },
  { song: "Baba ORiley", artist: "The Who", era: "70s", genre: "rock" },
  { song: "Behind Blue Eyes", artist: "The Who", era: "70s", genre: "rock" },
  { song: "Wont Get Fooled Again", artist: "The Who", era: "70s", genre: "rock" },
  { song: "Comfortably Numb", artist: "Pink Floyd", era: "70s", genre: "rock" },
  { song: "Wish You Were Here", artist: "Pink Floyd", era: "70s", genre: "rock" },
  { song: "Another Brick in the Wall", artist: "Pink Floyd", era: "70s", genre: "rock" },
  { song: "Time", artist: "Pink Floyd", era: "70s", genre: "rock" },
  { song: "Money", artist: "Pink Floyd", era: "70s", genre: "rock" },
  { song: "Shine On You Crazy Diamond", artist: "Pink Floyd", era: "70s", genre: "rock" },
  { song: "Layla", artist: "Eric Clapton", era: "70s", genre: "rock" },
  { song: "Tears in Heaven", artist: "Eric Clapton", era: "90s", genre: "classic" },
  { song: "Wonderful Tonight", artist: "Eric Clapton", era: "70s", genre: "classic" },
  { song: "Roxanne", artist: "The Police", era: "70s", genre: "rock" },
  { song: "Message in a Bottle", artist: "The Police", era: "70s", genre: "rock" },
  { song: "Every Breath You Take", artist: "The Police", era: "80s", genre: "rock" },
  { song: "Born to Run", artist: "Bruce Springsteen", era: "70s", genre: "rock" },
  { song: "Thunder Road", artist: "Bruce Springsteen", era: "70s", genre: "rock" },
  { song: "Dancing in the Dark", artist: "Bruce Springsteen", era: "80s", genre: "rock" },
  { song: "I Wanna Dance with Somebody", artist: "Whitney Houston", era: "80s", genre: "pop" },
  { song: "Billie Jean", artist: "Michael Jackson", era: "80s", genre: "pop" },
  { song: "Thriller", artist: "Michael Jackson", era: "80s", genre: "pop" },
  { song: "Beat It", artist: "Michael Jackson", era: "80s", genre: "pop" },
  { song: "Man in the Mirror", artist: "Michael Jackson", era: "80s", genre: "pop" },
  { song: "Smooth Criminal", artist: "Michael Jackson", era: "80s", genre: "pop" },
  { song: "Dangerous", artist: "Michael Jackson", era: "90s", genre: "pop" },
  { song: "Superstition", artist: "Stevie Wonder", era: "70s", genre: "r&b" },
  { song: "Higher Ground", artist: "Stevie Wonder", era: "70s", genre: "r&b" },
  { song: "Sir Duke", artist: "Stevie Wonder", era: "70s", genre: "r&b" },
  { song: "I Will Always Love You", artist: "Whitney Houston", era: "90s", genre: "pop" },
  { song: "Greatest Love of All", artist: "Whitney Houston", era: "80s", genre: "pop" },
  { song: "I Want It That Way", artist: "Backstreet Boys", era: "90s", genre: "pop" },

  // ─── 80s ───
  { song: "Sweet Dreams", artist: "Eurythmics", era: "80s", genre: "electronic" },
  { song: "Take On Me", artist: "a-ha", era: "80s", genre: "pop" },
  { song: "Dont Stop Believin", artist: "Journey", era: "80s", genre: "rock" },
  { song: "Livin on a Prayer", artist: "Bon Jovi", era: "80s", genre: "rock" },
  { song: "You Shook Me All Night Long", artist: "ACDC", era: "80s", genre: "rock" },
  { song: "Back in Black", artist: "ACDC", era: "80s", genre: "rock" },
  { song: "Highway to Hell", artist: "ACDC", era: "70s", genre: "rock" },
  { song: "Thunderstruck", artist: "ACDC", era: "90s", genre: "rock" },
  { song: "Pour Some Sugar on Me", artist: "Def Leppard", era: "80s", genre: "rock" },
  { song: "Photograph", artist: "Def Leppard", era: "80s", genre: "rock" },
  { song: "Every Rose Has Its Thorn", artist: "Poison", era: "80s", genre: "rock" },
  { song: "Dont You Forget About Me", artist: "Simple Minds", era: "80s", genre: "rock" },
  { song: "Tainted Love", artist: "Soft Cell", era: "80s", genre: "electronic" },
  { song: "Blue Monday", artist: "New Order", era: "80s", genre: "electronic" },
  { song: "Enola Gay", artist: "OMD", era: "80s", genre: "electronic" },
  { song: "Personal Jesus", artist: "Depeche Mode", era: "90s", genre: "electronic" },
  { song: "Enjoy the Silence", artist: "Depeche Mode", era: "90s", genre: "electronic" },
  { song: "Just Cant Get Enough", artist: "Depeche Mode", era: "80s", genre: "electronic" },
  { song: "Sweet Child O Mine", artist: "Guns N Roses", era: "80s", genre: "rock" },
  { song: "November Rain", artist: "Guns N Roses", era: "90s", genre: "rock" },
  { song: "Welcome to the Jungle", artist: "Guns N Roses", era: "80s", genre: "rock" },
  { song: "Paradise City", artist: "Guns N Roses", era: "80s", genre: "rock" },
  { song: "Africa", artist: "Toto", era: "80s", genre: "rock" },
  { song: "Rosanna", artist: "Toto", era: "80s", genre: "rock" },
  { song: "Hold the Line", artist: "Toto", era: "70s", genre: "rock" },
  { song: "Sultans of Swing", artist: "Dire Straits", era: "70s", genre: "rock" },
  { song: "Money for Nothing", artist: "Dire Straits", era: "80s", genre: "rock" },
  { song: "Brothers in Arms", artist: "Dire Straits", era: "80s", genre: "rock" },
  { song: "Your Song", artist: "Elton John", era: "70s", genre: "classic" },
  { song: "Rocket Man", artist: "Elton John", era: "70s", genre: "classic" },
  { song: "Tiny Dancer", artist: "Elton John", era: "70s", genre: "classic" },
  { song: "Candle in the Wind", artist: "Elton John", era: "70s", genre: "classic" },
  { song: "Crocodile Rock", artist: "Elton John", era: "70s", genre: "classic" },
  { song: "Bennie and the Jets", artist: "Elton John", era: "70s", genre: "classic" },
  { song: "Piano Man", artist: "Billy Joel", era: "70s", genre: "classic" },
  { song: "Uptown Girl", artist: "Billy Joel", era: "80s", genre: "pop" },
  { song: "We Didnt Start the Fire", artist: "Billy Joel", era: "80s", genre: "rock" },
  { song: "Its Still Rock and Roll to Me", artist: "Billy Joel", era: "80s", genre: "rock" },
  { song: "New York State of Mind", artist: "Billy Joel", era: "70s", genre: "classic" },
  { song: "Total Eclipse of the Heart", artist: "Bonnie Tyler", era: "80s", genre: "pop" },
  { song: "Holding Out for a Hero", artist: "Bonnie Tyler", era: "80s", genre: "pop" },
  { song: "Time After Time", artist: "Cyndi Lauper", era: "80s", genre: "pop" },
  { song: "Girls Just Want to Have Fun", artist: "Cyndi Lauper", era: "80s", genre: "pop" },
  { song: "True Colors", artist: "Cyndi Lauper", era: "80s", genre: "pop" },
  { song: "Like a Prayer", artist: "Madonna", era: "80s", genre: "pop" },
  { song: "Material Girl", artist: "Madonna", era: "80s", genre: "pop" },
  { song: "Vogue", artist: "Madonna", era: "90s", genre: "pop" },
  { song: "Crazy for You", artist: "Madonna", era: "80s", genre: "pop" },
  { song: "Express Yourself", artist: "Madonna", era: "80s", genre: "pop" },
  { song: "Sledgehammer", artist: "Peter Gabriel", era: "80s", genre: "rock" },
  { song: "In Your Eyes", artist: "Peter Gabriel", era: "80s", genre: "rock" },
  { song: "Red Rain", artist: "Peter Gabriel", era: "80s", genre: "rock" },
  { song: "Land of Confusion", artist: "Genesis", era: "80s", genre: "rock" },
  { song: "Invisible Touch", artist: "Genesis", era: "80s", genre: "rock" },
  { song: "Against All Odds", artist: "Phil Collins", era: "80s", genre: "pop" },
  { song: "In the Air Tonight", artist: "Phil Collins", era: "80s", genre: "rock" },
  { song: "Another Day in Paradise", artist: "Phil Collins", era: "80s", genre: "pop" },
  { song: "Sussudio", artist: "Phil Collins", era: "80s", genre: "pop" },
  { song: "With or Without You", artist: "U2", era: "80s", genre: "rock" },
  { song: "One", artist: "U2", era: "90s", genre: "rock" },
  { song: "Where the Streets Have No Name", artist: "U2", era: "80s", genre: "rock" },
  { song: "Sunday Bloody Sunday", artist: "U2", era: "80s", genre: "rock" },
  { song: "Beautiful Day", artist: "U2", era: "00s", genre: "rock" },
  { song: "Still Havent Found What Im Looking For", artist: "U2", era: "80s", genre: "rock" },
  { song: "Pride", artist: "U2", era: "80s", genre: "rock" },

  // ─── 90s ───
  { song: "Losing My Religion", artist: "REM", era: "90s", genre: "rock" },
  { song: "Everybody Hurts", artist: "REM", era: "90s", genre: "rock" },
  { song: "Man on the Moon", artist: "REM", era: "90s", genre: "rock" },
  { song: "Black Hole Sun", artist: "Soundgarden", era: "90s", genre: "rock" },
  { song: "Plush", artist: "Stone Temple Pilots", era: "90s", genre: "rock" },
  { song: "Creep", artist: "Radiohead", era: "90s", genre: "indie" },
  { song: "Karma Police", artist: "Radiohead", era: "90s", genre: "indie" },
  { song: "No Surprises", artist: "Radiohead", era: "90s", genre: "indie" },
  { song: "Fake Plastic Trees", artist: "Radiohead", era: "90s", genre: "indie" },
  { song: "Wonderwall", artist: "Oasis", era: "90s", genre: "rock" },
  { song: "Dont Look Back in Anger", artist: "Oasis", era: "90s", genre: "rock" },
  { song: "Champagne Supernova", artist: "Oasis", era: "90s", genre: "rock" },
  { song: "Live Forever", artist: "Oasis", era: "90s", genre: "rock" },
  { song: "Bitter Sweet Symphony", artist: "The Verve", era: "90s", genre: "rock" },
  { song: "Loser", artist: "Beck", era: "90s", genre: "indie" },
  { song: "Where Is My Mind", artist: "Pixies", era: "80s", genre: "indie" },
  { song: "Under the Bridge", artist: "Red Hot Chili Peppers", era: "90s", genre: "rock" },
  { song: "Californication", artist: "Red Hot Chili Peppers", era: "90s", genre: "rock" },
  { song: "Scar Tissue", artist: "Red Hot Chili Peppers", era: "90s", genre: "rock" },
  { song: "Otherside", artist: "Red Hot Chili Peppers", era: "90s", genre: "rock" },
  { song: "Soul to Squeeze", artist: "Red Hot Chili Peppers", era: "90s", genre: "rock" },
  { song: "Iris", artist: "Goo Goo Dolls", era: "90s", genre: "rock" },
  { song: "Slide", artist: "Goo Goo Dolls", era: "90s", genre: "rock" },
  { song: "Name", artist: "Goo Goo Dolls", era: "90s", genre: "rock" },
  { song: "SemiCharmed Life", artist: "Third Eye Blind", era: "90s", genre: "rock" },
  { song: "Jumper", artist: "Third Eye Blind", era: "90s", genre: "rock" },
  { song: "Tubthumping", artist: "Chumbawamba", era: "90s", genre: "pop" },
  { song: "Breakfast at Tiffanys", artist: "Deep Blue Something", era: "90s", genre: "rock" },
  { song: "Stay", artist: "Lisa Loeb", era: "90s", genre: "pop" },
  { song: "Torn", artist: "Natalie Imbruglia", era: "90s", genre: "pop" },
  { song: "Killing Me Softly", artist: "Fugees", era: "90s", genre: "r&b" },
  { song: "Ready or Not", artist: "Fugees", era: "90s", genre: "hiphop" },
  { song: "Doo Wop", artist: "Lauryn Hill", era: "90s", genre: "r&b" },
  { song: "Nothing Even Matters", artist: "Lauryn Hill", era: "90s", genre: "r&b" },
  { song: "No Scrubs", artist: "TLC", era: "90s", genre: "r&b" },
  { song: "Waterfalls", artist: "TLC", era: "90s", genre: "r&b" },
  { song: "Creep", artist: "TLC", era: "90s", genre: "r&b" },
  { song: "Lose Yourself", artist: "Eminem", era: "00s", genre: "hiphop" },
  { song: "Stan", artist: "Eminem", era: "00s", genre: "hiphop" },
  { song: "The Real Slim Shady", artist: "Eminem", era: "90s", genre: "hiphop" },
  { song: "Without Me", artist: "Eminem", era: "00s", genre: "hiphop" },
  { song: "My Name Is", artist: "Eminem", era: "90s", genre: "hiphop" },
  { song: "Hypnotize", artist: "Notorious BIG", era: "90s", genre: "hiphop" },
  { song: "Mo Money Mo Problems", artist: "Notorious BIG", era: "90s", genre: "hiphop" },
  { song: "Juicy", artist: "Notorious BIG", era: "90s", genre: "hiphop" },
  { song: "Big Poppa", artist: "Notorious BIG", era: "90s", genre: "hiphop" },
  { song: "California Love", artist: "2Pac", era: "90s", genre: "hiphop" },
  { song: "Changes", artist: "2Pac", era: "90s", genre: "hiphop" },
  { song: "Dear Mama", artist: "2Pac", era: "90s", genre: "hiphop" },
  { song: "Hit Em Up", artist: "2Pac", era: "90s", genre: "hiphop" },
  { song: "Gangstas Paradise", artist: "Coolio", era: "90s", genre: "hiphop" },
  { song: "Cant Hold Us Down", artist: "Missy Elliott", era: "90s", genre: "hiphop" },
  { song: "Get Ur Freak On", artist: "Missy Elliott", era: "00s", genre: "hiphop" },
  { song: "Work It", artist: "Missy Elliott", era: "00s", genre: "hiphop" },

  // ─── 00s ───
  { song: "In the End", artist: "Linkin Park", era: "00s", genre: "rock" },
  { song: "Numb", artist: "Linkin Park", era: "00s", genre: "rock" },
  { song: "Crawling", artist: "Linkin Park", era: "00s", genre: "rock" },
  { song: "Somewhere I Belong", artist: "Linkin Park", era: "00s", genre: "rock" },
  { song: "Breaking the Habit", artist: "Linkin Park", era: "00s", genre: "rock" },
  { song: "Faint", artist: "Linkin Park", era: "00s", genre: "rock" },
  { song: "What Ive Done", artist: "Linkin Park", era: "00s", genre: "rock" },
  { song: "Castle of Glass", artist: "Linkin Park", era: "10s", genre: "rock" },
  { song: "Chop Suey", artist: "System of a Down", era: "00s", genre: "metal" },
  { song: "Toxicity", artist: "System of a Down", era: "00s", genre: "metal" },
  { song: "Aerials", artist: "System of a Down", era: "00s", genre: "metal" },
  { song: "BYOB", artist: "System of a Down", era: "00s", genre: "metal" },
  { song: "Enter Sandman", artist: "Metallica", era: "90s", genre: "metal" },
  { song: "Master of Puppets", artist: "Metallica", era: "80s", genre: "metal" },
  { song: "Nothing Else Matters", artist: "Metallica", era: "90s", genre: "metal" },
  { song: "One", artist: "Metallica", era: "80s", genre: "metal" },
  { song: "Sad But True", artist: "Metallica", era: "90s", genre: "metal" },
  { song: "The Unforgiven", artist: "Metallica", era: "90s", genre: "metal" },
  { song: "Fade to Black", artist: "Metallica", era: "80s", genre: "metal" },
  { song: "For Whom the Bell Tolls", artist: "Metallica", era: "80s", genre: "metal" },
  { song: "Wherever I May Roam", artist: "Metallica", era: "90s", genre: "metal" },
  { song: "Creeping Death", artist: "Metallica", era: "80s", genre: "metal" },
  { song: "Battery", artist: "Metallica", era: "80s", genre: "metal" },
  { song: "Fuel", artist: "Metallica", era: "90s", genre: "metal" },
  { song: "Seek and Destroy", artist: "Metallica", era: "80s", genre: "metal" },
  { song: "Crazy Train", artist: "Ozzy Osbourne", era: "80s", genre: "metal" },
  { song: "Mr Crowley", artist: "Ozzy Osbourne", era: "80s", genre: "metal" },
  { song: "Bark at the Moon", artist: "Ozzy Osbourne", era: "80s", genre: "metal" },
  { song: "Iron Man", artist: "Black Sabbath", era: "70s", genre: "metal" },
  { song: "Paranoid", artist: "Black Sabbath", era: "70s", genre: "metal" },
  { song: "War Pigs", artist: "Black Sabbath", era: "70s", genre: "metal" },
  { song: "Sweet Leaf", artist: "Black Sabbath", era: "70s", genre: "metal" },
  { song: "NIB", artist: "Black Sabbath", era: "70s", genre: "metal" },
  { song: "Heaven and Hell", artist: "Black Sabbath", era: "80s", genre: "metal" },
  { song: "Symptom of the Universe", artist: "Black Sabbath", era: "70s", genre: "metal" },
  { song: "Children of the Grave", artist: "Black Sabbath", era: "70s", genre: "metal" },
  { song: "Breaking the Law", artist: "Judas Priest", era: "80s", genre: "metal" },
  { song: "Living After Midnight", artist: "Judas Priest", era: "80s", genre: "metal" },
  { song: "Youve Got Another Thing Comin", artist: "Judas Priest", era: "80s", genre: "metal" },
  { song: "Painkiller", artist: "Judas Priest", era: "90s", genre: "metal" },
  { song: "Electric Eye", artist: "Judas Priest", era: "80s", genre: "metal" },
  { song: "The Number of the Beast", artist: "Iron Maiden", era: "80s", genre: "metal" },
  { song: "Run to the Hills", artist: "Iron Maiden", era: "80s", genre: "metal" },
  { song: "The Trooper", artist: "Iron Maiden", era: "80s", genre: "metal" },
  { song: "Fear of the Dark", artist: "Iron Maiden", era: "90s", genre: "metal" },
  { song: "Hallowed Be Thy Name", artist: "Iron Maiden", era: "80s", genre: "metal" },
  { song: "2 Minutes to Midnight", artist: "Iron Maiden", era: "80s", genre: "metal" },
  { song: "Aces High", artist: "Iron Maiden", era: "80s", genre: "metal" },
  { song: "Wasted Years", artist: "Iron Maiden", era: "80s", genre: "metal" },
  { song: "Can I Play with Madness", artist: "Iron Maiden", era: "80s", genre: "metal" },
  { song: "Stranger in a Strange Land", artist: "Iron Maiden", era: "80s", genre: "metal" },
  { song: "Bring Me to Life", artist: "Evanescence", era: "00s", genre: "rock" },
  { song: "My Immortal", artist: "Evanescence", era: "00s", genre: "rock" },
  { song: "Going Under", artist: "Evanescence", era: "00s", genre: "rock" },
  { song: "Call Me When Youre Sober", artist: "Evanescence", era: "00s", genre: "rock" },
  { song: "Snow", artist: "Red Hot Chili Peppers", era: "00s", genre: "rock" },
  { song: "Dani California", artist: "Red Hot Chili Peppers", era: "00s", genre: "rock" },
  { song: "Tell Me Baby", artist: "Red Hot Chili Peppers", era: "00s", genre: "rock" },
  { song: "Hump de Bump", artist: "Red Hot Chili Peppers", era: "00s", genre: "rock" },
  { song: "Closer", artist: "Nine Inch Nails", era: "90s", genre: "electronic" },
  { song: "Hurt", artist: "Nine Inch Nails", era: "90s", genre: "rock" },
  { song: "Head Like a Hole", artist: "Nine Inch Nails", era: "90s", genre: "electronic" },
  { song: "Survivalism", artist: "Nine Inch Nails", era: "00s", genre: "electronic" },
  { song: "Personal Jesus", artist: "Johnny Cash", era: "00s", genre: "classic" },
  { song: "Hurt", artist: "Johnny Cash", era: "00s", genre: "classic" },
  { song: "Ring of Fire", artist: "Johnny Cash", era: "60s", genre: "classic" },
  { song: "Folsom Prison Blues", artist: "Johnny Cash", era: "60s", genre: "classic" },
  { song: "I Walk the Line", artist: "Johnny Cash", era: "60s", genre: "classic" },
  { song: "A Boy Named Sue", artist: "Johnny Cash", era: "60s", genre: "classic" },
  { song: "Get Rhythm", artist: "Johnny Cash", era: "60s", genre: "classic" },

  // ─── 10s/20s ───
  { song: "Somebody That I Used to Know", artist: "Gotye", era: "10s", genre: "pop" },
  { song: "Somebody I Used to Know", artist: "Gotye", era: "10s", genre: "pop" },
  { song: "Royal", artist: "Lorde", era: "10s", genre: "pop" },
  { song: "Royals", artist: "Lorde", era: "10s", genre: "pop" },
  { song: "Team", artist: "Lorde", era: "10s", genre: "pop" },
  { song: "Green Light", artist: "Lorde", era: "10s", genre: "pop" },
  { song: "Take Me to Church", artist: "Hozier", era: "10s", genre: "indie" },
  { song: "Someone New", artist: "Hozier", era: "10s", genre: "indie" },
  { song: "Work Song", artist: "Hozier", era: "10s", genre: "indie" },
  { song: "Sedated", artist: "Hozier", era: "10s", genre: "indie" },
  { song: "Jackie and Wilson", artist: "Hozier", era: "10s", genre: "indie" },
  { song: "From Eden", artist: "Hozier", era: "10s", genre: "indie" },
  { song: "Someone Like You", artist: "Adele", era: "10s", genre: "pop" },
  { song: "Hello", artist: "Adele", era: "10s", genre: "pop" },
  { song: "Rolling in the Deep", artist: "Adele", era: "10s", genre: "pop" },
  { song: "Skyfall", artist: "Adele", era: "10s", genre: "pop" },
  { song: "Set Fire to the Rain", artist: "Adele", era: "10s", genre: "pop" },
  { song: "When We Were Young", artist: "Adele", era: "10s", genre: "pop" },
  { song: "Chasing Pavements", artist: "Adele", era: "00s", genre: "pop" },
  { song: "Radioactive", artist: "Imagine Dragons", era: "10s", genre: "rock" },
  { song: "Demons", artist: "Imagine Dragons", era: "10s", genre: "rock" },
  { song: "Believer", artist: "Imagine Dragons", era: "10s", genre: "rock" },
  { song: "Thunder", artist: "Imagine Dragons", era: "10s", genre: "rock" },
  { song: "Whatever It Takes", artist: "Imagine Dragons", era: "10s", genre: "rock" },
  { song: "Birds", artist: "Imagine Dragons", era: "10s", genre: "rock" },
  { song: "Its Time", artist: "Imagine Dragons", era: "10s", genre: "rock" },
  { song: "On Top of the World", artist: "Imagine Dragons", era: "10s", genre: "rock" },
  { song: "Shots", artist: "Imagine Dragons", era: "10s", genre: "rock" },
  { song: "Walk the Moon", artist: "Shut Up and Dance", era: "10s", genre: "pop" },
  { song: "Shut Up and Dance", artist: "WALK THE MOON", era: "10s", genre: "pop" },
  { song: "The Nights", artist: "Avicii", era: "10s", genre: "electronic" },
  { song: "Wake Me Up", artist: "Avicii", era: "10s", genre: "electronic" },
  { song: "Hey Brother", artist: "Avicii", era: "10s", genre: "electronic" },
  { song: "Levels", artist: "Avicii", era: "10s", genre: "electronic" },
  { song: "Waiting for Love", artist: "Avicii", era: "10s", genre: "electronic" },
  { song: "Without You", artist: "Avicii", era: "10s", genre: "electronic" },
  { song: "SOS", artist: "Avicii", era: "10s", genre: "electronic" },
  { song: "Tough Love", artist: "Avicii", era: "10s", genre: "electronic" },
  { song: "Lonely Together", artist: "Avicii", era: "10s", genre: "electronic" },
  { song: "Get Lucky", artist: "Daft Punk", era: "10s", genre: "electronic" },
  { song: "Instant Crush", artist: "Daft Punk", era: "10s", genre: "electronic" },
  { song: "Lose Yourself to Dance", artist: "Daft Punk", era: "10s", genre: "electronic" },
  { song: "Give Life Back to Music", artist: "Daft Punk", era: "10s", genre: "electronic" },
  { song: "Around the World", artist: "Daft Punk", era: "90s", genre: "electronic" },
  { song: "One More Time", artist: "Daft Punk", era: "00s", genre: "electronic" },
  { song: "Harder Better Faster Stronger", artist: "Daft Punk", era: "00s", genre: "electronic" },
  { song: "Digital Love", artist: "Daft Punk", era: "00s", genre: "electronic" },
  { song: "Aerodynamic", artist: "Daft Punk", era: "00s", genre: "electronic" },
  { song: "Veridis Quo", artist: "Daft Punk", era: "00s", genre: "electronic" },
  { song: "Something About Us", artist: "Daft Punk", era: "00s", genre: "electronic" },
  { song: "Starlight", artist: "Muse", era: "00s", genre: "rock" },
  { song: "Supermassive Black Hole", artist: "Muse", era: "00s", genre: "rock" },
  { song: "Uprising", artist: "Muse", era: "00s", genre: "rock" },
  { song: "Knights of Cydonia", artist: "Muse", era: "00s", genre: "rock" },
  { song: "Hysteria", artist: "Muse", era: "00s", genre: "rock" },
  { song: "Time Is Running Out", artist: "Muse", era: "00s", genre: "rock" },
  { song: "Plug in Baby", artist: "Muse", era: "00s", genre: "rock" },
  { song: "Stockholm Syndrome", artist: "Muse", era: "00s", genre: "rock" },
  { song: "Bliss", artist: "Muse", era: "00s", genre: "rock" },
  { song: "Muscle Museum", artist: "Muse", era: "90s", genre: "rock" },
  { song: "Sunburn", artist: "Muse", era: "90s", genre: "rock" },
  { song: "Do I Wanna Know", artist: "Arctic Monkeys", era: "10s", genre: "indie" },
  { song: "R U Mine", artist: "Arctic Monkeys", era: "10s", genre: "indie" },
  { song: "Whyd You Only Call Me When Youre High", artist: "Arctic Monkeys", era: "10s", genre: "indie" },
  { song: "Arabella", artist: "Arctic Monkeys", era: "10s", genre: "indie" },
  { song: "505", artist: "Arctic Monkeys", era: "00s", genre: "indie" },
  { song: "Fluorescent Adolescent", artist: "Arctic Monkeys", era: "00s", genre: "indie" },
  { song: "Brianstorm", artist: "Arctic Monkeys", era: "00s", genre: "indie" },
  { song: "I Bet You Look Good on the Dancefloor", artist: "Arctic Monkeys", era: "00s", genre: "indie" },
  { song: "Fake Tales of San Francisco", artist: "Arctic Monkeys", era: "00s", genre: "indie" },
  { song: "The View from the Afternoon", artist: "Arctic Monkeys", era: "00s", genre: "indie" },
  { song: "Mardy Bum", artist: "Arctic Monkeys", era: "00s", genre: "indie" },
  { song: "When the Sun Goes Down", artist: "Arctic Monkeys", era: "00s", genre: "indie" },
  { song: "Teddy Picker", artist: "Arctic Monkeys", era: "00s", genre: "indie" },
  { song: "Old Yellow Bricks", artist: "Arctic Monkeys", era: "00s", genre: "indie" },
  { song: "The Hellcat Spangled Shalalala", artist: "Arctic Monkeys", era: "10s", genre: "indie" },
  { song: "Brick by Brick", artist: "Arctic Monkeys", era: "10s", genre: "indie" },
  { song: "Black Treacle", artist: "Arctic Monkeys", era: "10s", genre: "indie" },
  { song: "Reckless Serenade", artist: "Arctic Monkeys", era: "10s", genre: "indie" },
  { song: "Piledriver Waltz", artist: "Arctic Monkeys", era: "10s", genre: "indie" },
  { song: "Love Is a Laserquest", artist: "Arctic Monkeys", era: "10s", genre: "indie" },
  { song: "Suck It and See", artist: "Arctic Monkeys", era: "10s", genre: "indie" },
  { song: "She Looks Like Fun", artist: "Arctic Monkeys", era: "10s", genre: "indie" },
  { song: "One Point Perspective", artist: "Arctic Monkeys", era: "10s", genre: "indie" },
  { song: "American Sports", artist: "Arctic Monkeys", era: "10s", genre: "indie" },
  { song: "Tranquility Base Hotel Casino", artist: "Arctic Monkeys", era: "10s", genre: "indie" },
  { song: "Four Out of Five", artist: "Arctic Monkeys", era: "10s", genre: "indie" },
  { song: "Science Fiction", artist: "Arctic Monkeys", era: "10s", genre: "indie" },
  { song: "Sheffield Wednesday", artist: "Arctic Monkeys", era: "10s", genre: "indie" },
  { song: "Star Treatment", artist: "Arctic Monkeys", era: "10s", genre: "indie" },
  { song: "Golden Trunks", artist: "Arctic Monkeys", era: "10s", genre: "indie" },
  { song: "Batphone", artist: "Arctic Monkeys", era: "10s", genre: "indie" },
  { song: "The Ultracheese", artist: "Arctic Monkeys", era: "10s", genre: "indie" },
  { song: "Body Paint", artist: "Arctic Monkeys", era: "20s", genre: "indie" },
  { song: "There Better Be a Mirrorball", artist: "Arctic Monkeys", era: "20s", genre: "indie" },
  { song: "I Aint Quite Where I Think I Am", artist: "Arctic Monkeys", era: "20s", genre: "indie" },
  { song: "Sculptures of Anything Goes", artist: "Arctic Monkeys", era: "20s", genre: "indie" },
  { song: "Jet Skis on the Moat", artist: "Arctic Monkeys", era: "20s", genre: "indie" },
  { song: "Hello You", artist: "Arctic Monkeys", era: "20s", genre: "indie" },
  { song: "Mr Schwartz", artist: "Arctic Monkeys", era: "20s", genre: "indie" },
  { song: "Perfect Sense", artist: "Arctic Monkeys", era: "20s", genre: "indie" },

  // ─── Hans Zimmer / Soundtrack ───
  { song: "Time", artist: "Hans Zimmer", era: "10s", genre: "classic" },
  { song: "Cornfield Chase", artist: "Hans Zimmer", era: "10s", genre: "classic" },
  { song: "Now We Are Free", artist: "Hans Zimmer", era: "00s", genre: "classic" },
  { song: "Chevaliers de Sangreal", artist: "Hans Zimmer", era: "00s", genre: "classic" },
  { song: "Dream Is Collapsing", artist: "Hans Zimmer", era: "10s", genre: "classic" },
  { song: "Mountains", artist: "Hans Zimmer", era: "10s", genre: "classic" },
  { song: "Day One", artist: "Hans Zimmer", era: "10s", genre: "classic" },
  { song: "No Time for Caution", artist: "Hans Zimmer", era: "10s", genre: "classic" },
  { song: "S.T.A.Y.", artist: "Hans Zimmer", era: "10s", genre: "classic" },
  { song: "First Step", artist: "Hans Zimmer", era: "10s", genre: "classic" },
  { song: "Where Were Going", artist: "Hans Zimmer", era: "10s", genre: "classic" },
  { song: "Stay", artist: "Hans Zimmer", era: "10s", genre: "classic" },
  { song: "Out of Time", artist: "Hans Zimmer", era: "10s", genre: "classic" },
  { song: "Place in Paris", artist: "Hans Zimmer", era: "10s", genre: "classic" },
  { song: "Aura", artist: "Hans Zimmer", era: "10s", genre: "classic" },
  { song: "See What I See", artist: "Hans Zimmer", era: "10s", genre: "classic" },
  { song: "Run", artist: "Hans Zimmer", era: "10s", genre: "classic" },
  { song: "Catch Me If You Can", artist: "Hans Zimmer", era: "00s", genre: "classic" },
  { song: "The Kraken", artist: "Hans Zimmer", era: "00s", genre: "classic" },
  { song: "Drink Up Me Hearties", artist: "Hans Zimmer", era: "00s", genre: "classic" },
  { song: "Up Is Down", artist: "Hans Zimmer", era: "00s", genre: "classic" },
  { song: "Hoist the Colours", artist: "Hans Zimmer", era: "00s", genre: "classic" },
  { song: "One Day", artist: "Hans Zimmer", era: "00s", genre: "classic" },
  { song: "Honor Him", artist: "Hans Zimmer", era: "00s", genre: "classic" },
  { song: "A Way of Life", artist: "Hans Zimmer", era: "00s", genre: "classic" },
  { song: "Find Me with You", artist: "Hans Zimmer", era: "10s", genre: "classic" },
  { song: "Lose Control", artist: "Hans Zimmer", era: "10s", genre: "classic" },
  { song: "Convergence", artist: "Hans Zimmer", era: "10s", genre: "classic" },
  { song: "Day One Dark", artist: "Hans Zimmer", era: "10s", genre: "classic" },
  { song: "What Happens in Cuba", artist: "Hans Zimmer", era: "10s", genre: "classic" },
  { song: "A Morbid Taste for Purity", artist: "Hans Zimmer", era: "10s", genre: "classic" },
  { song: "Look on the Bright Side of Life", artist: "Hans Zimmer", era: "10s", genre: "classic" },

  // ─── Misc Classics ───
  { song: "Bitter Sweet Symphony", artist: "The Verve", era: "90s", genre: "rock" },
  { song: "Mad World", artist: "Gary Jules", era: "00s", genre: "classic" },
  { song: "Mad World", artist: "Tears for Fears", era: "80s", genre: "rock" },
  { song: "Shout", artist: "Tears for Fears", era: "80s", genre: "rock" },
  { song: "Everybody Wants to Rule the World", artist: "Tears for Fears", era: "80s", genre: "rock" },
  { song: "Head Over Heels", artist: "Tears for Fears", era: "80s", genre: "rock" },
  { song: "Melt with You", artist: "Modern English", era: "80s", genre: "rock" },
  { song: "Just Like Heaven", artist: "The Cure", era: "80s", genre: "rock" },
  { song: "Lovesong", artist: "The Cure", era: "80s", genre: "rock" },
  { song: "Friday Im in Love", artist: "The Cure", era: "90s", genre: "rock" },
  { song: "Pictures of You", artist: "The Cure", era: "80s", genre: "rock" },
  { song: "Boys Dont Cry", artist: "The Cure", era: "80s", genre: "rock" },
  { song: "Close to Me", artist: "The Cure", era: "80s", genre: "rock" },
  { song: "In Between Days", artist: "The Cure", era: "80s", genre: "rock" },
  { song: "A Forest", artist: "The Cure", era: "80s", genre: "rock" },
  { song: "Lullaby", artist: "The Cure", era: "80s", genre: "rock" },
  { song: "High", artist: "The Cure", era: "90s", genre: "rock" },
  { song: "The End of the World", artist: "The Cure", era: "00s", genre: "rock" },
  { song: "Never Enough", artist: "The Cure", era: "90s", genre: "rock" },
  { song: "Wrong Number", artist: "The Cure", era: "90s", genre: "rock" },
  { song: "Cut Here", artist: "The Cure", era: "00s", genre: "rock" },
  { song: "The Only One", artist: "The Cure", era: "00s", genre: "rock" },
  { song: "Freak Show", artist: "The Cure", era: "00s", genre: "rock" },
  { song: "The Hungry Ghost", artist: "The Cure", era: "00s", genre: "rock" },
  { song: "Sleep When I Am Dead", artist: "The Cure", era: "80s", genre: "rock" },
  { song: "Hot Hot Hot", artist: "The Cure", era: "80s", genre: "rock" },
  { song: "Lets Go to Bed", artist: "The Cure", era: "80s", genre: "rock" },
  { song: "The Walk", artist: "The Cure", era: "80s", genre: "rock" },
  { song: "The Love Cats", artist: "The Cure", era: "80s", genre: "rock" },
  { song: "The Caterpillar", artist: "The Cure", era: "80s", genre: "rock" },
  { song: "Inbetween Days", artist: "The Cure", era: "80s", genre: "rock" },
  { song: "Six Different Ways", artist: "The Cure", era: "80s", genre: "rock" },
  { song: "Push", artist: "The Cure", era: "80s", genre: "rock" },
  { song: "Baby Jane", artist: "The Cure", era: "80s", genre: "rock" },
  { song: "The Blood", artist: "The Cure", era: "80s", genre: "rock" },
  { song: "Close to Me Remix", artist: "The Cure", era: "90s", genre: "rock" },

  // ─── More Pop/Rock Legends ───
  { song: "Dont Look Back in Anger", artist: "Oasis", era: "90s", genre: "rock" },
  { song: "Whatever", artist: "Oasis", era: "90s", genre: "rock" },
  { song: "Roll with It", artist: "Oasis", era: "90s", genre: "rock" },
  { song: "Some Might Say", artist: "Oasis", era: "90s", genre: "rock" },
  { song: "Morning Glory", artist: "Oasis", era: "90s", genre: "rock" },
  { song: "Whats the Story Morning Glory", artist: "Oasis", era: "90s", genre: "rock" },
  { song: "DYou Know What I Mean", artist: "Oasis", era: "90s", genre: "rock" },
  { song: "Stand by Me", artist: "Oasis", era: "90s", genre: "rock" },
  { song: "All Around the World", artist: "Oasis", era: "90s", genre: "rock" },
  { song: "Dont Go Away", artist: "Oasis", era: "90s", genre: "rock" },
  { song: "Go Let It Out", artist: "Oasis", era: "00s", genre: "rock" },
  { song: "Fuckin in the Bushes", artist: "Oasis", era: "00s", genre: "rock" },
  { song: "Lets All Make Believe", artist: "Oasis", era: "00s", genre: "rock" },
  { song: "The Hindu Times", artist: "Oasis", era: "00s", genre: "rock" },
  { song: "Stop Crying Your Heart Out", artist: "Oasis", era: "00s", genre: "rock" },
  { song: "Songbird", artist: "Oasis", era: "00s", genre: "rock" },
  { song: "Little by Little", artist: "Oasis", era: "00s", genre: "rock" },
  { song: "Lyla", artist: "Oasis", era: "00s", genre: "rock" },
  { song: "The Importance of Being Idle", artist: "Oasis", era: "00s", genre: "rock" },
  { song: "Let There Be Love", artist: "Oasis", era: "00s", genre: "rock" },
  { song: "The Shock of the Lightning", artist: "Oasis", era: "00s", genre: "rock" },
  { song: "Falling Down", artist: "Oasis", era: "00s", genre: "rock" },
  { song: "Im Outta Time", artist: "Oasis", era: "00s", genre: "rock" },
  { song: "Bag It Up", artist: "Oasis", era: "00s", genre: "rock" },
  { song: "Waiting for the Rapture", artist: "Oasis", era: "00s", genre: "rock" },
  { song: "The Turning", artist: "Oasis", era: "00s", genre: "rock" },
  { song: "High Horse Lady", artist: "Oasis", era: "00s", genre: "rock" },
  { song: "To Be Where Theres Life", artist: "Oasis", era: "00s", genre: "rock" },
  { song: "Aint Got Nothin", artist: "Oasis", era: "00s", genre: "rock" },
  { song: "The Nature of Reality", artist: "Oasis", era: "00s", genre: "rock" },
  { song: "Soldier On", artist: "Oasis", era: "00s", genre: "rock" },

  // ─── Coldplay ───
  { song: "Yellow", artist: "Coldplay", era: "00s", genre: "rock" },
  { song: "The Scientist", artist: "Coldplay", era: "00s", genre: "rock" },
  { song: "Clocks", artist: "Coldplay", era: "00s", genre: "rock" },
  { song: "Fix You", artist: "Coldplay", era: "00s", genre: "rock" },
  { song: "Speed of Sound", artist: "Coldplay", era: "00s", genre: "rock" },
  { song: "Viva la Vida", artist: "Coldplay", era: "00s", genre: "rock" },
  { song: "Paradise", artist: "Coldplay", era: "10s", genre: "rock" },
  { song: "Adventure of a Lifetime", artist: "Coldplay", era: "10s", genre: "rock" },
  { song: "Hymn for the Weekend", artist: "Coldplay", era: "10s", genre: "rock" },
  { song: "Something Just Like This", artist: "Coldplay", era: "10s", genre: "electronic" },
  { song: "A Sky Full of Stars", artist: "Coldplay", era: "10s", genre: "electronic" },
  { song: "In My Place", artist: "Coldplay", era: "00s", genre: "rock" },
  { song: "God Put a Smile upon Your Face", artist: "Coldplay", era: "00s", genre: "rock" },
  { song: "Dont Panic", artist: "Coldplay", era: "00s", genre: "rock" },
  { song: "Trouble", artist: "Coldplay", era: "00s", genre: "rock" },
  { song: "Shiver", artist: "Coldplay", era: "00s", genre: "rock" },
  { song: "Sparks", artist: "Coldplay", era: "00s", genre: "rock" },
  { song: "Everythings Not Lost", artist: "Coldplay", era: "00s", genre: "rock" },
  { song: "Life Is for Living", artist: "Coldplay", era: "00s", genre: "rock" },
  { song: "Amsterdam", artist: "Coldplay", era: "00s", genre: "rock" },
  { song: " politik", artist: "Coldplay", era: "00s", genre: "rock" },
  { song: "Warning Sign", artist: "Coldplay", era: "00s", genre: "rock" },
  { song: "A Whisper", artist: "Coldplay", era: "00s", genre: "rock" },
  { song: "A Rush of Blood to the Head", artist: "Coldplay", era: "00s", genre: "rock" },
  { song: "Daylight", artist: "Coldplay", era: "00s", genre: "rock" },
  { song: "Green Eyes", artist: "Coldplay", era: "00s", genre: "rock" },
  { song: "X and Y", artist: "Coldplay", era: "00s", genre: "rock" },
  { song: "What If", artist: "Coldplay", era: "00s", genre: "rock" },
  { song: "White Shadows", artist: "Coldplay", era: "00s", genre: "rock" },
  { song: "Low", artist: "Coldplay", era: "00s", genre: "rock" },
  { song: "Hardest Part", artist: "Coldplay", era: "00s", genre: "rock" },
  { song: "Swallowed in the Sea", artist: "Coldplay", era: "00s", genre: "rock" },
  { song: "Twisted Logic", artist: "Coldplay", era: "00s", genre: "rock" },
  { song: "Til Kingdom Come", artist: "Coldplay", era: "00s", genre: "rock" },
  { song: "How You See the World", artist: "Coldplay", era: "00s", genre: "rock" },
  { song: "Gravity", artist: "Coldplay", era: "00s", genre: "rock" },
  { song: "Proof", artist: "Coldplay", era: "00s", genre: "rock" },
  { song: "Things I Dont Understand", artist: "Coldplay", era: "00s", genre: "rock" },
  { song: "The World Turned Upside Down", artist: "Coldplay", era: "00s", genre: "rock" },
  { song: "Sleeping Sun", artist: "Coldplay", era: "00s", genre: "rock" },
  { song: "Gold in Them Hills", artist: "Coldplay", era: "00s", genre: "rock" },

  // ─── The Weeknd / Bruno Mars ───
  { song: "Blinding Lights", artist: "The Weeknd", era: "20s", genre: "pop" },
  { song: "Save Your Tears", artist: "The Weeknd", era: "20s", genre: "pop" },
  { song: "Starboy", artist: "The Weeknd", era: "10s", genre: "r&b" },
  { song: "The Hills", artist: "The Weeknd", era: "10s", genre: "r&b" },
  { song: "Cant Feel My Face", artist: "The Weeknd", era: "10s", genre: "pop" },
  { song: "I Feel It Coming", artist: "The Weeknd", era: "10s", genre: "r&b" },
  { song: "Call Out My Name", artist: "The Weeknd", era: "10s", genre: "r&b" },
  { song: "Pray for Me", artist: "The Weeknd", era: "10s", genre: "r&b" },
  { song: "Uptown Funk", artist: "Bruno Mars", era: "10s", genre: "pop" },
  { song: "24K Magic", artist: "Bruno Mars", era: "10s", genre: "pop" },
  { song: "Thats What I Like", artist: "Bruno Mars", era: "10s", genre: "pop" },
  { song: "Locked Out of Heaven", artist: "Bruno Mars", era: "10s", genre: "pop" },
  { song: "Grenade", artist: "Bruno Mars", era: "10s", genre: "pop" },
  { song: "Just the Way You Are", artist: "Bruno Mars", era: "10s", genre: "pop" },
  { song: "When I Was Your Man", artist: "Bruno Mars", era: "10s", genre: "pop" },
  { song: "Marry You", artist: "Bruno Mars", era: "10s", genre: "pop" },
  { song: "Treasure", artist: "Bruno Mars", era: "10s", genre: "pop" },
  { song: "Runaway Baby", artist: "Bruno Mars", era: "10s", genre: "pop" },
  { song: "Young Girls", artist: "Bruno Mars", era: "10s", genre: "pop" },
  { song: "Moonshine", artist: "Bruno Mars", era: "10s", genre: "pop" },
  { song: "Natalie", artist: "Bruno Mars", era: "10s", genre: "pop" },
  { song: "Show Me", artist: "Bruno Mars", era: "10s", genre: "pop" },
  { song: "Money Make Her Smile", artist: "Bruno Mars", era: "10s", genre: "pop" },
  { song: "If I Knew", artist: "Bruno Mars", era: "10s", genre: "pop" },
  { song: "Gorilla", artist: "Bruno Mars", era: "10s", genre: "pop" },
  { song: "Finesse", artist: "Bruno Mars", era: "10s", genre: "pop" },
  { song: "Chunky", artist: "Bruno Mars", era: "10s", genre: "pop" },
  { song: "Perm", artist: "Bruno Mars", era: "10s", genre: "pop" },
  { song: "Straight Up and Down", artist: "Bruno Mars", era: "10s", genre: "pop" },
  { song: "Calling All My Lovelies", artist: "Bruno Mars", era: "10s", genre: "pop" },
  { song: "Finesse Remix", artist: "Bruno Mars", era: "10s", genre: "pop" },
  { song: "Wake Up in the Sky", artist: "Bruno Mars", era: "10s", genre: "pop" },
  { song: "Please Me", artist: "Bruno Mars", era: "10s", genre: "pop" },
  { song: "Die With a Smile", artist: "Bruno Mars", era: "20s", genre: "pop" },
  { song: "Die With a Smile", artist: "Lady Gaga", era: "20s", genre: "pop" },
  { song: "Die With a Smile", artist: "Lady Gaga Bruno Mars", era: "20s", genre: "pop" },
  { song: "Applause", artist: "Lady Gaga", era: "10s", genre: "pop" },
  { song: "Bad Romance", artist: "Lady Gaga", era: "00s", genre: "pop" },
  { song: "Poker Face", artist: "Lady Gaga", era: "00s", genre: "pop" },
  { song: "Alejandro", artist: "Lady Gaga", era: "10s", genre: "pop" },
  { song: "Telephone", artist: "Lady Gaga", era: "10s", genre: "pop" },
  { song: "Just Dance", artist: "Lady Gaga", era: "00s", genre: "pop" },
  { song: "Born This Way", artist: "Lady Gaga", era: "10s", genre: "pop" },
  { song: "Judas", artist: "Lady Gaga", era: "10s", genre: "pop" },
  { song: "The Edge of Glory", artist: "Lady Gaga", era: "10s", genre: "pop" },
  { song: "Yo and I", artist: "Lady Gaga", era: "10s", genre: "pop" },
  { song: "Marry the Night", artist: "Lady Gaga", era: "10s", genre: "pop" },
  { song: "Shallow", artist: "Lady Gaga", era: "10s", genre: "pop" },
  { song: "Always Remember Us This Way", artist: "Lady Gaga", era: "10s", genre: "pop" },
  { song: "Ill Never Love Again", artist: "Lady Gaga", era: "10s", genre: "pop" },
  { song: "Rain on Me", artist: "Lady Gaga", era: "20s", genre: "pop" },
  { song: "Stupid Love", artist: "Lady Gaga", era: "20s", genre: "pop" },
  { song: "911", artist: "Lady Gaga", era: "20s", genre: "pop" },
  { song: "Hold My Hand", artist: "Lady Gaga", era: "20s", genre: "pop" },
  { song: "Bloody Mary", artist: "Lady Gaga", era: "20s", genre: "pop" },
  { song: "Disease", artist: "Lady Gaga", era: "20s", genre: "pop" },
  { song: "The Cure", artist: "Lady Gaga", era: "10s", genre: "pop" },

  // ─── Misc ───
  { song: "All Star", artist: "Smash Mouth", era: "90s", genre: "rock" },
  { song: "Walkin on the Sun", artist: "Smash Mouth", era: "90s", genre: "rock" },
  { song: "I Believe in a Thing Called Love", artist: "The Darkness", era: "00s", genre: "rock" },
  { song: "Mambo No 5", artist: "Lou Bega", era: "90s", genre: "pop" },
  { song: "Smooth", artist: "Santana", era: "90s", genre: "pop" },
  { song: "Maria Maria", artist: "Santana", era: "00s", genre: "pop" },
  { song: "Bitter Sweet Symphony", artist: "The Verve", era: "90s", genre: "rock" },
  { song: "The Drugs Dont Work", artist: "The Verve", era: "90s", genre: "rock" },
  { song: "Lucky Man", artist: "The Verve", era: "90s", genre: "rock" },
  { song: "Sonnet", artist: "The Verve", era: "90s", genre: "rock" },
  { song: "Space and Time", artist: "The Verve", era: "90s", genre: "rock" },
  { song: "Velvet Morning", artist: "The Verve", era: "90s", genre: "rock" },
  { song: "Come On", artist: "The Verve", era: "90s", genre: "rock" },
  { song: "Weeping Willow", artist: "The Verve", era: "90s", genre: "rock" },
  { song: "Catching the Butterfly", artist: "The Verve", era: "90s", genre: "rock" },
  { song: "Neon Wilderness", artist: "The Verve", era: "90s", genre: "rock" },
  { song: "One Day", artist: "The Verve", era: "90s", genre: "rock" },
  { song: "This Time", artist: "The Verve", era: "90s", genre: "rock" },
  { song: "History", artist: "The Verve", era: "90s", genre: "rock" },
  { song: "Rolling People", artist: "The Verve", era: "90s", genre: "rock" },
  { song: "The Rolling People", artist: "The Verve", era: "90s", genre: "rock" },
  { song: "Life Aint So Easy", artist: "The Verve", era: "90s", genre: "rock" },
  { song: "But the Soul Sings On", artist: "The Verve", era: "90s", genre: "rock" },
  { song: "But Soul Sings On", artist: "The Verve", era: "90s", genre: "rock" },
  { song: "Life Aint So Easy", artist: "The Verve", era: "90s", genre: "rock" },
  { song: "Deepless Sea", artist: "The Verve", era: "90s", genre: "rock" },
  { song: "Repeater", artist: "The Verve", era: "90s", genre: "rock" },
  { song: "Gravity Grave", artist: "The Verve", era: "90s", genre: "rock" },
  { song: "A Man Called Sun", artist: "The Verve", era: "90s", genre: "rock" },
  { song: "She Is a Vision", artist: "The Verve", era: "90s", genre: "rock" },
  { song: "Change My Life", artist: "The Verve", era: "90s", genre: "rock" },
] as const;

/** Normalize a song/artist string for dedup matching.
 *  Lowercase, remove "feat."/"ft." suffixes, remove punctuation. */
export function normalizeForMusicMatch(s: string): string {
  return s.toLowerCase()
    .replace(/\s*\(feat\.[^)]*\)\s*/gi, " ")
    .replace(/\s*feat\.\s.*$/gi, " ")
    .replace(/\s*ft\.\s.*$/gi, " ")
    .replace(/[^a-z0-9]/gi, "")
    .trim();
}

/** Check if a song+artist pair is in the Hall of Fame. */
export function isInHallOfFame(song: string, artist: string): HallOfFameEntry | null {
  const normSong = normalizeForMusicMatch(song);
  const normArtist = normalizeForMusicMatch(artist);
  if (!normSong || !normArtist) return null;
  for (const entry of HALL_OF_FAME) {
    if (normalizeForMusicMatch(entry.song) === normSong &&
        normalizeForMusicMatch(entry.artist) === normArtist) {
      return entry;
    }
  }
  return null;
}
