/**
 * src/entry/cron-maintenance.ts
 * v12.0.0 — Layer 3: Daily Maintenance Cron (every 24 hours).
 *
 * This cron runs once per day at midnight UTC (`0 0 * * *`) and
 * handles end-of-day maintenance tasks.
 *
 * RESPONSIBILITIES:
 *   ✅ Generate tomorrow's daily plan (with fresh random scheduledTime per window)
 *   ✅ Clean expired KV data (old plans, stale dedup records, old logs)
 *   ✅ Reset daily counters (provider stats, queue metrics)
 *   ✅ Validate configuration integrity
 *   ✅ Send a daily summary to the admin (optional)
 *
 * DOES NOT:
 *   ❌ Publish posts (Layer 1 handles this)
 *   ❌ Refresh providers (Layer 2 handles this)
 *
 * PLAN GENERATION:
 *   The daily plan is generated HERE, not on-demand. Each slot gets
 *   a fresh random `scheduledTime` within its posting window. This
 *   time is stored in KV and NEVER regenerated during the day —
 *   ensuring the random jitter is stable and predictable.
 *
 *   If the plan already exists (e.g., generated by a manual dashboard
 *   action), it is NOT overwritten. This prevents disrupting a
 *   manually-curated plan.
 *
 * KV USAGE (per 24h tick):
 *   1 tick/day × (plan generation + cleanup + counter reset)
 *   ≈ 15 reads, 10 writes/day
 *
 * See V12_ARCHITECTURE.md §5 for the full design rationale.
 */

import type { Env, Container } from "../types/env";
import { acquireTickLock } from "../services/tick-lock";
import { formatDateInZone } from "../primitives/time";

const LAST_LOG_KEY = "fredy:tick:lastLog";
const LAST_TICK_KEY = "fredy:tick:lastTick";
/** KV keys for old daily plans — cleaned up daily. */
const PLAN_PREFIXES = ["fredy:strategy:plan:", "fredy:sched:slots:"];

export interface CronMaintenanceDeps {
  readonly env: Env;
  readonly container: Container;
  readonly ctx: ExecutionContext;
}

/**
 * Layer 3 handler — invoked by Cloudflare cron `0 0 * * *`.
 */
export async function cronMaintenanceHandler(deps: CronMaintenanceDeps): Promise<void> {
  const { env, container, ctx } = deps;
  ctx.waitUntil(runDailyMaintenance(container, env));
}

/**
 * Daily maintenance: plan generation + cleanup + counter reset.
 */
async function runDailyMaintenance(container: Container, env: Env): Promise<void> {
  const startTime = Date.now();
  const log: string[] = [];

  const tickLock = await acquireTickLock(container.kv, 120); // 2min for maintenance
  if (!tickLock.acquired) {
    await container.kv.setJson(LAST_LOG_KEY, {
      time: Date.now(),
      tickTime: startTime,
      layer: "daily-maintenance",
      skipped: true,
      reason: "lock_held",
      log: ["skipped: lock held"],
    }, 3600).catch(() => {});
    return;
  }

  try {
    log.push("daily-maintenance started");

    const settings = await container.config.getSettings(Number(env.ADMIN_ID ?? "0")).catch(() => null);
    if (!settings) {
      log.push("settings load failed — aborting maintenance");
      return;
    }

    const tz = settings.scheduler.timezone || "UTC";
    const today = formatDateInZone(startTime, tz);
    const tomorrow = formatDateInZone(startTime + 24 * 60 * 60 * 1000, tz);

    // ── 1. GENERATE TOMORROW'S PLAN (with fresh random scheduledTime) ────
    // The plan is generated ONCE per day. Each slot's scheduledTime is
    // random within its window and stable for the entire day.
    try {
      // Check if tomorrow's plan already exists (don't overwrite manual generation).
      const existing = await container.kv.getJson(`fredy:strategy:plan:${tomorrow}`).catch(() => null);
      if (existing) {
        log.push(`tomorrow's plan (${tomorrow}) already exists — skipping generation`);
      } else {
        const plan = await container.strategyEngine.generatePlan(tomorrow);
        log.push(`✅ generated plan for ${tomorrow}: ${plan.posts.length} posts`);
        // Log the random scheduled times for visibility.
        for (const post of plan.posts) {
          log.push(`  slot #${post.index}: window ${post.time}-${post.windowEnd ?? post.time} → scheduled ${post.scheduledTime ?? post.time} (${post.category}/${post.provider ?? "?"})`);
        }
      }
    } catch (error) {
      log.push(`❌ plan generation failed: ${error instanceof Error ? error.message : String(error)}`);
    }

    // ── 2. ENSURE TODAY'S PLAN EXISTS (safety net) ────
    try {
      const todayPlan = await container.kv.getJson(`fredy:strategy:plan:${today}`).catch(() => null);
      if (!todayPlan) {
        await container.strategyEngine.generatePlan(today);
        log.push(`✅ generated missing plan for today (${today})`);
      }
    } catch (error) {
      log.push(`today plan check failed: ${error instanceof Error ? error.message : String(error)}`);
    }

    // ── 3. CLEAN EXPIRED KV DATA ────
    // Remove old daily plans (keep today + yesterday for debugging).
    const cleanedCount = await cleanupOldPlans(container, today);
    if (cleanedCount > 0) {
      log.push(`🧹 cleaned ${cleanedCount} old plan(s) from KV`);
    }

    // ── 4. FLUSH BATCHED STATS ────
    await container.kv.flushAllStats().catch(() => {});
    log.push("stats flushed");

    // ── 5. LOG DAILY SUMMARY (for the admin dashboard) ────
    try {
      const engineSummary = container.providerEngine?.getSummary?.();
      if (engineSummary) {
        log.push(`provider engine: ${engineSummary.enabledProviders}/${engineSummary.totalProviders} enabled, ${engineSummary.healthyProviders} healthy, ${engineSummary.dueForRefresh} due`);
      }
    } catch {
      // non-fatal
    }

    log.push("daily-maintenance complete");

  } finally {
    await tickLock.release();

    await container.kv.set(LAST_TICK_KEY, String(startTime)).catch(() => {});
    await container.kv.setJson(LAST_LOG_KEY, {
      time: Date.now(),
      tickTime: startTime,
      layer: "daily-maintenance",
      durationMs: Date.now() - startTime,
      log,
    }, 7200).catch(() => {});
  }
}

/**
 * Remove daily-plan KV entries older than yesterday.
 * Keeps today + yesterday for debugging/auditing.
 */
async function cleanupOldPlans(container: Container, today: string): Promise<number> {
  let cleaned = 0;
  try {
    // List all keys with the plan prefixes.
    for (const prefix of PLAN_PREFIXES) {
      const keys = await container.kv.list(prefix).catch(() => []);
      for (const key of keys) {
        // Extract the date from the key: "fredy:strategy:plan:2026-07-20" → "2026-07-20"
        const dateStr = key.split(":").pop();
        if (!dateStr || dateStr.length !== 10) continue;
        // Keep today and yesterday (dateStr >= today means today or future).
        if (dateStr >= today) continue;
        // Delete old plans.
        await container.kv.delete(key).catch(() => {});
        cleaned++;
      }
    }
  } catch {
    // non-fatal — cleanup is best-effort
  }
  return cleaned;
}
